import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Sequis Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Navbar web */}
        <div className="w-full hidden lg:block">
          <ul className="grid grid-cols-3 justify-items-start mx-8">
            <li>All Articles</li>
            <li>Fashion</li>
            <li>Food</li>
            <li>Travel</li>
            <li>Film</li>
            <li>Business</li>
          </ul>
        </div>

        {/* Navbar mobile */}
        <div className="justify-between flex lg:hidden">
          <span>Logo</span>
          <button>
            <svg viewBox="0 0 100 80" width="40" height="40">
              <rect width="100" height="15"></rect>
              <rect y="30" width="100" height="15"></rect>
              <rect y="60" width="100" height="15"></rect>
            </svg>
          </button>
        </div>

        {/* Articles */}
        <div className="flex flex-col my-12 px-8 lg:px-0">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-y-12">
            {/* Card */}
            <div className="flex flex-col items-center gap-y-6">
              <Image
                src="https://picsum.photos/600/400"
                width={600}
                height={400}
                className="rounded rounded-lg"
              ></Image>
              <span className="border border-black p-2 rounded-full text-xs">
                By <span className="font-bold">Christopher Johnson</span>
              </span>
              <span className="font-medium text-2xl">
                10 Simple Way to Cook Quinoa
              </span>
            </div>

            <div className="flex flex-col items-center gap-y-6">
              <Image
                src="https://picsum.photos/600/400"
                width={600}
                height={400}
                className="rounded rounded-lg"
              ></Image>
              <span className="border border-black p-2 rounded-full text-xs">
                By <span className="font-bold">Christopher Johnson</span>
              </span>
              <span className="font-medium text-2xl">
                10 Simple Way to Cook Quinoa
              </span>
            </div>

            <div className="flex flex-col items-center gap-y-6">
              <Image
                src="https://picsum.photos/600/400"
                width={600}
                height={400}
                className="rounded rounded-lg"
              ></Image>
              <span className="border border-black p-2 rounded-full text-xs">
                By <span className="font-bold">Christopher Johnson</span>
              </span>
              <span className="font-medium text-2xl">
                10 Simple Way to Cook Quinoa
              </span>
            </div>

            <div className="flex flex-col items-center gap-y-6">
              <Image
                src="https://picsum.photos/600/400"
                width={600}
                height={400}
                className="rounded rounded-lg"
              ></Image>
              <span className="border border-black p-2 rounded-full text-xs">
                By <span className="font-bold">Christopher Johnson</span>
              </span>
              <span className="font-medium text-2xl">
                10 Simple Way to Cook Quinoa
              </span>
            </div>
          </div>

          <span className="border border-black py-6 px-8 uppercase self-center my-12">
            More Articles
          </span>
        </div>

        {/* Footer */}
        <div className="flex flex-col items-center bg-black text-white py-12 gap-y-6 text-center">
          <span className="text-4xl font-bold">Empowering Minds</span>
          <span className="text-gray-400 px-8 text-xl lg:px-0">
            Insights and Strategies for Personal and Professional Growth
          </span>

          <div className="grid lg:grid-cols-3 gap-12 px-12">
            {/* Card */}
            <div className="flex flex-col items-center gap-y-6">
              <Image
                src="https://picsum.photos/600/400"
                width={600}
                height={400}
                className="rounded rounded-lg"
              ></Image>
              <span className="border border-white p-2 rounded-full text-xs">
                By <span className="font-bold">Christopher Johnson</span>
              </span>
              <span className="font-medium text-xl text-gray-300">
                10 Simple Way to Cook Quinoa
              </span>
            </div>

            <div className="flex flex-col items-center gap-y-6">
              <Image
                src="https://picsum.photos/600/400"
                width={600}
                height={400}
                className="rounded rounded-lg"
              ></Image>
              <span className="border border-white p-2 rounded-full text-xs">
                By <span className="font-bold">Christopher Johnson</span>
              </span>
              <span className="font-medium text-xl text-gray-300">
                10 Simple Way to Cook Quinoa
              </span>
            </div>

            <div className="flex flex-col items-center gap-y-6">
              <Image
                src="https://picsum.photos/600/400"
                width={600}
                height={400}
                className="rounded rounded-lg"
              ></Image>
              <span className="border border-white p-2 rounded-full text-xs">
                By <span className="font-bold">Christopher Johnson</span>
              </span>
              <span className="font-medium text-xl text-gray-300">
                10 Simple Way to Cook Quinoa
              </span>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
